[package]
name = "voodoo-doll"
version = "0.1.4"
authors = ["msk- <mattkingston@gmail.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1.6" }
warp = "0.3"
futures = "0.3"
fspiox-api = { git = "https://github.com/partiallyordered/fspiox-api", rev = "e0a48a0f703a6a6ece098b3bc93a70cf33e505b0", features = ["fsp_http"] }
# fspiox-api = { path = "/home/msk/projects/github.com/msk-/fspiox-api/" ,features = ["fsp_http"] }
serde_json = "1"
serde = { version = "1", features = ["derive"] }
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls"] }
mojaloop-api = { git = "https://github.com/partiallyordered/mojaloop-api", rev = "08a89f17f6d5c6165d70277e1e5cea36b4be9b57" }
# mojaloop-api = { path = "/home/msk/projects/github.com/msk-/mojaloop-api/" }
gethostname = "0.2"
thiserror = "1.0"
