apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: voodoo-doll
build:
  artifacts:
  - image: ghcr.io/partiallyordered/voodoo-doll
    docker:
      dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
    - kubernetes
